// The content of this file was generated by IBM Cloud
// Do not modify it as it might get overridden
module.exports = (app) => {
    const basepath = "/v1";
  
    require('./public')(app);

    // Monitoring
    require('./health')(app);

    // Application routes
    require('./queries')(app, basepath);
};  